<?php

namespace VuBa\Repository;

/**
 * ClickAttachmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClickAttachmentRepository extends \Doctrine\ORM\EntityRepository
{
}
