<?php

namespace VuBa\Repository;

/**
 * ClickProposalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClickProposalRepository extends \Doctrine\ORM\EntityRepository
{
}
