<?php

namespace VuBa\Repository;

/**
 * ClickCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClickCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
